Hw02 express
Slapchenko/nodejs-contacts-api pull request #1
Opened 2023-01-27 22:11 UTC by Slapchenko

Прошу перевірити роботу

2023-01-28 15:11 UTC, Eastvarga requested changes
Є зауваження

2023-01-28 15:11 UTC, Eastvarga commented on controllers/contacts/add.js
> +  const result = await operations.add(req.body);
Не використовуйте обширні поняття для назв методів 
add - погано
addContact  - інтуітивно зрозуміло що повинно робити - додавати контакт не зрозуміло до чого, але
createContact -  створити контакт - зовсім добре зрозуміло що повинна робити функція

2023-01-28 15:11 UTC, Eastvarga commented on controllers/contacts/add.js
> +  });
тут зайві данні у відповіді
res.status(201).json(result) достатньо

2023-01-28 15:11 UTC, Eastvarga commented on controllers/contacts/getAll.js
> +  const contacts = await operations.getAll();
теж іменування поправте усюди - краще умпортувати самі функції ніж об'ект, у котромупотім функцію використовуєте як метод

2023-01-28 15:11 UTC, Eastvarga commented on models/contacts/removeById.js
> +  contactList.splice(index, 1);
не використовуйте методи котрі мутують масив. Знайдіть іньше рішення без мутації масиву contactList

2023-01-28 15:11 UTC, Eastvarga commented on models/contacts/removeById.js
> +  }
щось дивна перевірка після того як ви -1 використали const removeContact = contactList[-1]; (це у випадку коли пошук індексу повернув -1)

2023-01-28 15:11 UTC, Eastvarga commented on models/contacts/updateById.js
> +  contactList[index] = { id, ...body };
Метод цільовий для універсальності методу апдейту краще додайте розпилення попередньо існуючого - тоді цей метод можна використовувати для оновлення по любому з полів та по любій кількості цих полів

2023-01-28 15:11 UTC, Eastvarga commented on routes/api/contacts.js
> +router.put("/:id", validation(contactSchema), ctrlWrapper(ctrl.updateById));
ctrl - взагалі незрозуміла назва, додайте зрозумілості Вашому коду.

2023-01-28 15:11 UTC, Eastvarga commented on server.js
> +app.listen(3002, () => {
додайте файл конфігурацій, для ініціалізування змінних серверу та потім імпортуйте їх туди де треба

2023-01-30 22:49 UTC, Slapchenko commented on controllers/contacts/add.js
> +  const result = await operations.add(req.body);
Дякую за пораду. Виправлено.

2023-01-30 22:51 UTC, Slapchenko commented on controllers/contacts/add.js
> +  });
Трохи пеперобив логіку відправки. Додав відповідну функцію: /helpers/setSuccessResponse.js

2023-01-30 22:51 UTC, Slapchenko commented on controllers/contacts/getAll.js
> +  const contacts = await operations.getAll();
Виправлено

2023-01-30 22:52 UTC, Slapchenko commented on models/contacts/removeById.js
> +  contactList.splice(index, 1);
Переробив логіку у т.ч. по апдейту

2023-01-30 22:52 UTC, Slapchenko commented on models/contacts/removeById.js
> +  }
Дійсно. Переробив

2023-01-30 22:52 UTC, Slapchenko commented on models/contacts/updateById.js
> +  contactList[index] = { id, ...body };
Переробив

2023-01-30 22:52 UTC, Slapchenko commented on routes/api/contacts.js
> +router.put("/:id", validation(contactSchema), ctrlWrapper(ctrl.updateById));
Виправлено

2023-01-30 22:57 UTC, Slapchenko commented on server.js
> +app.listen(3002, () => {
Якщо я правильно вас зрозумів... Зробив так: встановив dotenv, до файлу .env додав PORT, в файлі [server.js] написав відповідний код.

2023-01-31 20:14 UTC, Eastvarga requested changes
Є зауваження.

2023-01-31 20:14 UTC, Eastvarga commented on controllers/contacts/createContactController.js
> +  res.json(setSuccessResponse(200, newContact));
Добре постаралися, але
res.json(setSuccessResponse(200, newContact));
res.satus(200).json(responseBody); - ось як сетиться статус та тіло відповіді - тіло може мати будьяку форму однак тіло не сетить статус відповіді це просто корисне навантаження payload відповіді

2023-01-31 20:14 UTC, Eastvarga commented on helpers/setSuccessResponse.js
> +};
Ось це дуже непотрібний код, нажаль

2023-01-31 20:14 UTC, Eastvarga commented on models/contacts/removeContactById.js
> +  );
Це погана логіка - двічи проходити по масиву не потрібно щоб видалити контакт - все можна зробити і однією фільтрацією в калбек функції котрої записати контакт до змінної при співпадінні з айді видалення а умовою фільтрації буде не співпадіння з видаляємим айді

2023-01-31 20:14 UTC, Eastvarga commented on models/contacts/updateContactById.js
> +  }
не потрібно це, у методі мап є другий аргумент індекс поточного елемента - просто запишіть його у змінну та потім по ньому витягніть вже оновлений елемент - або запишить сам елемент у змінну котру  оголосили попередньо

2023-01-31 22:37 UTC, Slapchenko commented on controllers/contacts/createContactController.js
> +  res.json(setSuccessResponse(200, newContact));
Виправлено

2023-01-31 22:38 UTC, Slapchenko commented on helpers/setSuccessResponse.js
> +};
Видалив

2023-01-31 23:01 UTC, Slapchenko commented on models/contacts/removeContactById.js
> +  );
Переробив

2023-01-31 23:12 UTC, Slapchenko commented on models/contacts/updateContactById.js
> +  }
Виправлено

2023-02-01 17:51 UTC, Eastvarga approved these changes

2023-02-01 18:01 UTC, merged