Hw04 auth
Slapchenko/nodejs-contacts-api pull request #3
Opened 2023-02-05 23:05 UTC by Slapchenko

2023-02-06 17:30 UTC, Eastvarga requested changes
Є зауваження

2023-02-06 17:30 UTC, Eastvarga commented on controllers/auth/getCurrentUserController.js
> +  );
хіба в  req.user не поточний юзер? навіщо ще раз до бази запит робити?

2023-02-06 17:30 UTC, Eastvarga commented on controllers/auth/signupUserController.js
> +  res.status(201).json(newUser);
повернення паролю чи його хешу дуже погана думка

2023-02-06 17:30 UTC, Eastvarga commented on middlewares/authMiddleware.js
> +    const { id } = jwt.verify(token, SECRET_KEY);
а що буде якщо токен пустий або не визначений? чому токен не перевіряєте?

2023-02-06 17:30 UTC, Eastvarga commented on routes/api/contacts.js
> +router.get("/:id", errorHandler(getContactByIdController));
authMiddleware -  чому не захистили цей раут?

2023-02-06 17:30 UTC, Eastvarga commented on routes/api/contacts.js
> +router.delete("/:id", errorHandler(removeContactByIdController));
видалення не захищене мідлваром авторізації - це дивне

2023-02-06 17:30 UTC, Eastvarga commented on routes/api/contacts.js
> +  validationMiddleware(contactSchema),
теж саме

2023-02-06 17:30 UTC, Eastvarga commented on routes/api/contacts.js
>    "/:id/favorite",
теж саме

2023-02-11 23:51 UTC, Slapchenko commented on controllers/auth/getCurrentUserController.js
> +  );
Дісно. Виправив.

2023-02-12 00:42 UTC, Slapchenko commented on controllers/auth/signupUserController.js
> +  res.status(201).json(newUser);
Олександре, це не думка. Це не уважність :)

2023-02-12 00:52 UTC, Slapchenko commented on middlewares/authMiddleware.js
> +    const { id } = jwt.verify(token, SECRET_KEY);
Виправив

2023-02-12 00:56 UTC, Slapchenko commented on routes/api/contacts.js
> +router.get("/:id", errorHandler(getContactByIdController));
Додав

2023-02-12 00:57 UTC, Slapchenko commented on routes/api/contacts.js
> +router.delete("/:id", errorHandler(removeContactByIdController));
Додав

2023-02-12 00:57 UTC, Slapchenko commented on routes/api/contacts.js
> +  validationMiddleware(contactSchema),
Додав

2023-02-12 00:59 UTC, Slapchenko commented on routes/api/contacts.js
>    "/:id/favorite",
Додав

2023-02-12 09:53 UTC, Eastvarga approved these changes

2023-02-12 09:53 UTC, merged